### ISSUE TITLE
[Bug] iOS

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/open-stage-control#647] opened 2020-08-30 09:54 UTC
Hi,
With O-S-C 1.0.4, running in Debian Testing, and a client Chrome 85.0(updated today) for iOS (13.5.1 for iPad 6th gen) and ardour-control (my custom version) loaded, i've theses issues :
- Can't scroll in the panels
- Loading very slow
- After background / forground, left and right strips are missing : 
![IMG_20200830_113522](https://user-images.githubusercontent.com/5098493/91656179-f3981800-eab6-11ea-80a4-0af733b46e60.jpg)

With safari (to get fullscreen working and avoid sleep), i just got nothing :
![IMG_20200830_113542](https://user-images.githubusercontent.com/5098493/91656209-39ed7700-eab7-11ea-94f5-98f7a6e93350.jpg)

It's a regression from v0.49. With it I could got it in signet with Safari and got it in fullscreen, without sleep.
Thank you again for the work !

**Comment by jean-emmanuel** [comment] 2020-09-02 10:16
I've only been able to test it on iOS 13.3, 13.4 and 14 and couldn't reproduce the bug.

**Comment by wargreen** [comment] 2020-09-02 22:58
What's your browser ?

**Comment by jean-emmanuel** [comment] 2020-09-03 18:25
On iOS it doesn't make a relevant difference : due to apple's policy it's always safari's engine running under the hood, the rest is merely cosmetic / branding .

**Comment by jean-emmanuel** [comment] 2020-12-06 20:39
I'm gonna go ahead and close it for now since. Feel free to reopen with up to date informations.

**Closed by jean-emmanuel** 2020-12-06 20:39 UTC
