### ISSUE TITLE
REAPER panel

### ISSUE THREAD

**Issue by ThrashJazzAssassin** [jean-emmanuel/open-stage-control#127] opened 2018-01-13 12:43 UTC
I made a panel for REAPER:

https://github.com/ThrashJazzAssassin/REAPER-OSC-panels

**Comment by jean-emmanuel** [comment] 2018-01-14 10:06
Awesome, thank you for sharing, I'll add an community examples section to the documentation :)

**Comment by ThrashJazzAssassin** [comment] 2018-01-15 02:23
Open-Stage-Control is so nice to work with, fast, nice to look at and has never crashed. Well done and thank you so much.

I'll post the panel to REAPER forums shortly. Just wanted to show you it first and tweak it a little. Thanks for adding it to your docs. Obviously feel free to modify it and use it as you wish.

**Comment by jean-emmanuel** [comment] 2018-01-15 12:43
Thanks a lot :)

Your screenshot actually showed me a bug with the icon font I hadn't noticed yet, will be fixed in next release !

**Comment by jean-emmanuel** [comment] 2018-01-31 17:17
Included in v0.23, cheers !

**Closed by jean-emmanuel** 2018-01-31 17:17 UTC

**Comment by ThrashJazzAssassin** [comment] 2018-02-01 00:08
Amazing.

Please could you have a look at the json I just uploaded. - v0.1.1
On the AUX FX page, the bottom 2 rows of faders are linked and I don't understand why. Each row is cloned+1 and the top 2 are fine. Have I found a bug or (more likely) have I done something wrong?

Is there a more elegant way to use @{parent.variables}?

**Comment by jean-emmanuel** [comment] 2018-02-01 08:01
Can't reproduce here, are you using the latest release ?

**Comment by ThrashJazzAssassin** [comment] 2018-02-01 09:26
Using newest v0.23.0

Yeah, sorry, it's working fine now after a restart.

**Comment by jean-emmanuel** [comment] 2018-02-01 09:31
Ok feel free to open another issue if it happens again (if it does, please try to describe a reproduction procedure to help debugging). 

> Is there a more elegant way to use @{parent.variables}?

You're doing just fine ;)

**Comment by ThrashJazzAssassin** [comment] 2018-03-23 16:51
Hi. I just noticed that some things in my REAPER panel is broken (clones in page2) and I can't figure out why. Could someone please have a look? Thanks

**Comment by jean-emmanuel** [comment] 2018-03-23 19:56
I found the piece of code that's causing this regression, will fix it soon.

**Comment by jean-emmanuel** [comment] 2018-03-26 21:47
should be fixed in 0.28.1
