### ISSUE TITLE
building and running on android

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#405] opened 2018-10-25 12:12 UTC
I know there is already an issue for this (https://github.com/jean-emmanuel/open-stage-control/issues/404), but it mainly seems focus on windows for now...

This is promising, but I couldn't get o-s-c to work for now. (but I think we are almost there)

So I tried termux on my Samsung Galaxy S6.

First, install and setup termux:
https://termux.com/
then do setup the storage and permissions for termux:
https://wiki.termux.com/wiki/Termux-setup-storage

Next, you must copy your private key to be able to log in on your phone

Or you can type these commands directly on your phone...

```
$ uname -a
Linux localhost 3.10.61-13830439 #1 SMP PREEMPT Wed Jun 20 16:32:45 KST 2018 aarch64 Android
```
```
$ apt-get install nodejs git python2 make g++ -y --no-install-recommends
$ mkdir build
$ cd build
$ git clone https://github.com/jean-emmanuel/open-stage-control.git
$ cd open-stage-control
```

node-sass and serialport modules have to be compiled. python2, make, g++ are needed for this.

(I get a warning during compilation:
npm WARN deprecated cardinal-spline-js@2.3.9: Package no longer supported. Contact support@npmjs.com for more info.)

to build node-sass, follow these instructions:
https://blog.akehir.com/2017/05/building-node-sass-libsass-python.html

then:
```
$ npm install
$ npm run build
```

then:

```
$ node app/ -n -d
```

I get this:
```
Running with node
App available at http://127.0.0.1:8080 & http://10.61.194.101:8080
A JavaScript error occurred in the main process:
Trace: { Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at Module.require2 (/data/data/com.termux/files/home/build/open-stage-control/app/node_modules/vmodule/lib/require.js:12:10)
    at Module.<anonymous> (/data/data/com.termux/files/home/build/open-stage-control/app/node_modules/radish/radish.js:130:15)
    at Module.bound [as require] (/data/data/com.termux/files/home/build/open-stage-control/app/node_modules/lodash/dist/lodash.js:957:21)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/build/open-stage-control/app/main/callbacks.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module.module.exports (/data/data/com.termux/files/home/build/open-stage-control/app/node_modules/infuser/lib/compile.js:33:25) code: 'MODULE_NOT_FOUND' }
    at process.on (/data/data/com.termux/files/home/build/open-stage-control/app/main/main.js:19:17)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:491:27)
```

Then, connection with chrome to localhost:8080, I see the waiting screen ' connecting to server' (see attached screenshot)

![osc android](https://user-images.githubusercontent.com/193917/47499204-a9610280-d85f-11e8-82e9-1eaf08598e1c.png)

@jean-emmanuel any hint, or something I could do to test?

When accessing the phone from my PC, I see the websocke connection, and fonts are downloaded, then.. same spinning circle... ;-(

**Comment by cyberic99** [comment] 2018-10-25 13:31
it works now!

I have to test on a bigger table now. (Termux needs at least Android 6.0)

**Comment by jean-emmanuel** [comment] 2018-10-25 13:33
wow, good job

**Comment by cyberic99** [comment] 2018-10-25 13:42
> wow, good job

thx!

There are a lot of cheap android tablets so this can be really useful to get o-s-c running directly on them (event if you still need *something* to control ;-))

I'll try to make an official termux  package

**Comment by cyberic99** [comment] 2018-10-25 13:58
> does it run with decent performances ?

I didn't  rally test it for now.

But I was able to launch chrome on my phone, open a session, open the same session locally on my pc, and I verified that they  were synchronized

As you know I have a quite complex session, and some 'fold' buttins, evrything seems to react quickly

But again, now that I know it works, I'll test it with a bigger tablet and report here

**Comment by cyberic99** [comment] 2018-10-26 09:34
@jean-emmanuel is the ``npm run package`` script supposed to run on android?

I wanted to run it to package the app more easily

```
$ npm run package

> open-stage-control-builder@0.38.4 package /home/builder/.termux-build/open-stage-control/src
> npm run build-css && npm run build-launcher-js && npm run build-browser-js -- --prod && node scripts/package.js


> open-stage-control-builder@0.38.4 build-css /home/builder/.termux-build/open-stage-control/src
> node scripts/build-css.js


> open-stage-control-builder@0.38.4 build-launcher-js /home/builder/.termux-build/open-stage-control/src
> node scripts/build-launcher.js > app/launcher/scripts.js


> open-stage-control-builder@0.38.4 build-browser-js /home/builder/.termux-build/open-stage-control/src
> node scripts/build-browser.js "--prod"

Building minified js bundle for production... This may take a while... 
Error: Cannot find module 'vertx' from '/home/builder/.termux-build/open-stage-control/src/node_modules/gyronorm/dist'
    at /home/builder/.termux-build/open-stage-control/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/builder/.termux-build/open-stage-control/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/builder/.termux-build/open-stage-control/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/builder/.termux-build/open-stage-control/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/builder/.termux-build/open-stage-control/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/builder/.termux-build/open-stage-control/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
/home/builder/.termux-build/open-stage-control/src/scripts/build-browser.js:93
            convert.toHtml(
                    ^

TypeError: Cannot read property 'toHtml' of undefined
    at Readable.output.on (/home/builder/.termux-build/open-stage-control/src/scripts/build-browser.js:93:21)
    at emitOne (events.js:116:13)
    at Readable.emit (events.js:211:7)
    at Labeled.<anonymous> (/home/builder/.termux-build/open-stage-control/src/node_modules/read-only-stream/index.js:28:44)
    at emitOne (events.js:116:13)
    at Labeled.emit (events.js:211:7)
    at Labeled.<anonymous> (/home/builder/.termux-build/open-stage-control/src/node_modules/stream-splicer/index.js:130:18)
    at emitOne (events.js:116:13)
    at Labeled.emit (events.js:211:7)
    at Deps.<anonymous> (/home/builder/.termux-build/open-stage-control/src/node_modules/stream-splicer/index.js:130:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! open-stage-control-builder@0.38.4 build-browser-js: `node scripts/build-browser.js "--prod"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the open-stage-control-builder@0.38.4 build-browser-js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/builder/.npm/_logs/2018-10-26T08_56_14_806Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! open-stage-control-builder@0.38.4 package: `npm run build-css && npm run build-launcher-js && npm run build-browser-js -- --prod && node scripts/package.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the open-stage-control-builder@0.38.4 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/builder/.npm/_logs/2018-10-26T08_56_15_004Z-debug.log
```

Sorry, I can't understand those hyndreds of npm packages with thousands of dependencies ;-)

Is it becausevertx was only an implicit dependency of electron, so it is not installed on android?

**Comment by jean-emmanuel** [comment] 2018-10-26 09:53
> @jean-emmanuel is the npm run package script supposed to run on android?

Just to be clear, o-s-c was not supposed to run on android, expect errors ;)

`npm run package` = `npm run build` + fetch electron binaries, so there is no chance for it to work. However the error happens during `npm run build` and seem to be triggered by an odd import in one of the dependencies (not related to electron), what's puzzling me is that I can't reproduce it here.

**Comment by cyberic99** [comment] 2018-10-26 10:00
I know, I can only reproduce it on android, and not on x86....

(fyi the arch is aarch64)

> Just to be clear, o-s-c was not supposed to run on android, expect errors ;)

yes, of course

But in fact o-s-c *thinks* it is running  on linux, I think it has no way to know it is android

> what's puzzling me is that I can't reproduce it here.

I couldn; t either. Only on android, not on x86...

In fact, o-s-c built correctly, all I have to do now is to copy the needed files in /usr/lib etc to get a correct package

So I thought npm package would be great for this.

I can also copy some files by hand...

Is there a way to obtain a directory containing only the needed (and minified) files to run o-s-c, without the sources?

thx

**Comment by jean-emmanuel** [comment] 2018-10-26 10:18
I pushed a `npm run package-node` that does what you want. You'll need to:
```
npm install
npm run package-node
# run !
node dist/open-stage-control-node 
```

**Comment by cyberic99** [comment] 2018-10-26 11:46
> I pushed a `npm run package-node` that does what you want.

Thx a lot!

I'll try it

**Comment by cyberic99** [comment] 2018-10-26 15:53
For those interrested, here is the build.sh I made to build o-s-c on termux:
```
TERMUX_PKG_HOMEPAGE=https://osc.ammd.net/
TERMUX_PKG_DESCRIPTION="Open Stage Control"
TERMUX_PKG_MAINTAINER="-"
TERMUX_PKG_DEPENDS="nodejs"
TERMUX_PKG_BUILDDEPENDS="python2 make g++"
TERMUX_PKG_VERSION=0.38.4-git
COMMITID=d23552ca367afe52975b4272b1fd704780106053
TERMUX_PKG_SHA256=570444e923e2b7e6f001b8b4f94782a0d979330184f1321b01d97e11e373118b
#TERMUX_PKG_SRCURL=https://github.com/jean-emmanuel/open-stage-control/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SRCURL=https://github.com/jean-emmanuel/open-stage-control/archive/${COMMITID}.tar.gz

TERMUX_PKG_BUILD_IN_SRC=yes
TERMUX_PKG_PLATFORM_INDEPENDENT=yes
TERMUX_NDK_VERSION="18"

termux_step_make() {
    npm install
    npm run package-node
}

termux_step_make_install() {
    mkdir -p ${TERMUX_PREFIX}/bin
    mkdir -p ${TERMUX_PREFIX}/share
    mv dist/open-stage-control-node dist/open-stage-control && cp -a dist/open-stage-control ${TERMUX_PREFIX}/share/
    echo -e "#!/bin/sh\nnode ${TERMUX_PREFIX}/share/open-stage-control/ $@" > ${TERMUX_PREFIX}/bin/open-stage-control
    chmod +x ${TERMUX_PREFIX}/bin/open-stage-control
}
```

@jean-emmanuel , if you are not against it, I'll try to do a pull request to integrate o-s-c directly into termux. It will open a wide range of devices to o-s-c (yes, they could already use o-s-c with a browser, but now they can *run* o-s-c as well ;-))

**Comment by jean-emmanuel** [comment] 2018-10-26 16:12
Nice ! Nothing to add, except you might wanna set yourself as the termux package's maintainer.

**Comment by cyberic99** [comment] 2018-10-26 16:37
I was hesitating due to the spam it could generate.... :-(
I should probably remove the builddepends...
Not sure, I will restart everything from a clean environment

**Comment by jean-emmanuel** [comment] 2018-10-26 18:01
I'm adding a -node package to the release binaries, you'll just have to download it from here and skip the `termux_step_make` step !

**Comment by cyberic99** [comment] 2018-10-26 21:47
Great, thanks!
But maybe it would be better to add a proper .deb package which could be installed directly on termux

Or even better, to include the package into the official termux repos, so users will be able to install it normally with apt-get ?

**Comment by jean-emmanuel** [comment] 2018-10-26 22:40
Yep, but I'd rather not do it myself, if u know what I mean... :wink:

**Comment by cyberic99** [comment] 2018-10-27 05:30
Yeah, right, I get it :-)
I'll put myself as a maintainer, but... 
I'm sure some users will open issues here anyway :-)

So do you want me to open a pull request on termux-packages?

After thinking about it, Should be easy enough to download the .zip in termux....

**Comment by jean-emmanuel** [comment] 2018-10-27 07:16
Maybe a fine tutorial would be enough then

**Comment by jean-emmanuel** [comment] 2018-10-27 10:42
I managed to strip out all the unnecessary files from the package, the zip file is 2.5mb now !

**Comment by cyberic99** [comment] 2018-10-27 20:04
Yeah, this rocks!

about the node-only version...
maybe you could include a small shell wrapper called open-stage-control-server that would call node? (and display an error message if node is not.installed?)
This would make it even easier for new users

I'll write a tutorial soon

**Comment by cyberic99** [comment] 2018-10-28 20:58
I think this might be doable with thr same script in osx, linux, and termux.
it does not have to be vrry simple since the user won't need to modify it....

It just has to launch node with the correct path (that will be hardcoded in the package anyway)

For termux, a bit a sed magic could be needed, because the path are a bit weird...

**Comment by cyberic99** [comment] 2018-11-08 10:40
@jean-emmanuel it seems that ``npm run package-node`` feature is not prsent in the docs yet

**Comment by jean-emmanuel** [comment] 2018-11-20 09:11
It is now, thanks. Closing since the job on my side seems to be done, I leave the platform specific scripts to the package maintainers (example: https://aur.archlinux.org/packages/open-stage-control-node-git/)

**Closed by jean-emmanuel** 2018-11-20 09:11 UTC
