### ISSUE TITLE
[Bug] Panel shows scrollbar after geometry update, but is on 100% width

### ISSUE THREAD

**Issue by MagnusReichel** [jean-emmanuel/open-stage-control#710] opened 2021-04-24 17:35 UTC
Please provide as much contextual informations as possible:

It's harmless and just a visual bug, but I'll post it here for completeness.
The bug just occurs in Editor, not in the front-end UI.

Here's the minimal description for reproduction:

I have a button with geometry width set to
``#{@{BTN_expand} == 0 ? 
50 : 
100}%``

BTN_expand is a button inside of the panel that allows the panel to be expanded or compressed (like written in the code). It has width set to 100%.
The code works as expected, but whenever the panel compressed, it shows a scrollbar for width. After clicking somewhere (no matter where) the scrollbar dissolves.

So as I said ;-) Nothing special, but I'll put it here anyways.

- Open Stage Control version 1.9.1
- Win & Mac

![Bug report](https://user-images.githubusercontent.com/83134034/115967561-949a7e00-a533-11eb-8d1b-10209fb56cc5.png)

**Comment by jean-emmanuel** [comment] 2021-04-28 10:48
Thanks for the report, the issue is due to the outline generated by the editor to indicate current selection, which is only updated when selection changes. I'm not sure I'll fix it, but I'll keep the ticket open in case I have an idea.

**Comment by jean-emmanuel** [comment] 2021-12-20 10:32
Fixed with 6b7663100388e4797e6d9c81648e4563fec2c340 (to be included in next release).

**Closed by jean-emmanuel** 2021-12-20 10:32 UTC
