### ISSUE TITLE
Javascript error with splitted range

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#179] opened 2018-03-03 16:28 UTC
I get a json parse error when using the transport_range widget.
[open_stage_control_bitwig.zip](https://github.com/jean-emmanuel/open-stage-control/files/1777655/open_stage_control_bitwig.zip)

**Comment by kdejaeger** [comment] 2018-03-03 16:31
However there was also a /position url in bitwig that I can use with a normal fader. And that works find.
So this issue is not important to me anymore.

**Comment by jean-emmanuel** [comment] 2018-03-03 16:48
Couldn't not reproduce the issue with your file, I've tested the range's split option and does seem to work fine when either `true` or `["/address/1", "/address/2"]`.

In the future please consider giving a little more information to help debugging and note that other users here might encounter the same problem as you, closing the issue because you don't care anymore isn't quite the good thing to do here.

**Comment by kdejaeger** [comment] 2018-03-03 19:02
Here' s the error:
`$ A JavaScript error occurred in the main process: Uncaught Exception:
SyntaxError: Unexpected token G in JSON at position 0
    at JSON.parse (<anonymous>)
    at Socket.receive (C:\Users\koen\IdeaProjects\open-stage-control\app\main\ipc\client.js:81:31)
    at WebSocket.socket.onmessage (C:\Users\koen\IdeaProjects\open-stage-control\app\main\ipc\client.js:38:18)
    at WebSocket.onMessage (C:\Users\koen\IdeaProjects\open-stage-control\app\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (C:\Users\koen\IdeaProjects\open-stage-control\app\node_modules\ws\lib\websocket.js:137:47)
    at Receiver.dataMessage (C:\Users\koen\IdeaProjects\open-stage-control\app\node_modules\ws\lib\receiver.js:409:14)
    at Receiver.getData (C:\Users\koen\IdeaProjects\open-stage-control\app\node_modules\ws\lib\receiver.js:347:12)
    at Receiver.startLoop (C:\Users\koen\IdeaProjects\open-stage-control\app\node_modules\ws\lib\receiver.js:143:16)
`

**Comment by jean-emmanuel** [comment] 2018-03-03 19:07
Hmm, looks like a malformed osc address, could you paste the `split` property here please ?

**Comment by kdejaeger** [comment] 2018-03-03 19:14
Error: The specified packet was not recognized as a valid OSC message or bundle. Packet was: {
  "address": " /position/--,/position/++/low",
  "args": [
    {
      "type": "f",
      "value": -8
    }
  ]
}

**Comment by kdejaeger** [comment] 2018-03-03 19:16
I had the zip file in my first comment with the json file.

**Comment by jean-emmanuel** [comment] 2018-03-03 19:18
Ok, your split property is malformed, try `["/position/--", "/position/++/low"]`. However, there is a bug that seem to break the socket under these conditions.

**Comment by jean-emmanuel** [comment] 2018-03-03 19:27
I've pushed a fix to prevent this error to break anything and just print the malformed address to help fix it.

**Comment by kdejaeger** [comment] 2018-03-03 19:33
I see now the problem was the space of the beginning of the address: "  /position ....

**Comment by jean-emmanuel** [comment] 2018-03-03 21:41
Ok cool !

**Closed by jean-emmanuel** 2018-03-03 21:41 UTC
