### ISSUE TITLE
OSC does not work on my iPad Pro (Chrome + iOS)

### ISSUE THREAD

**Issue by mrpastewart** [jean-emmanuel/open-stage-control#78] opened 2017-08-01 21:32 UTC
For some reason OSC will not run on my iPad Pro 10.5 it will load the main screen but will not run any of the demos nor allow you to enter the editor by creating new or browsing. I am using chrome 60.

**Comment by jean-emmanuel** [comment] 2017-08-02 10:28
Hi, thanks for your feedback,
- does this occur with the latest release (0.18.0) or with the online demo ?
- can you run the server from a terminal and check for error messages ?

**Comment by mrpastewart** [comment] 2017-08-03 23:49
This is occurring with the online demo. I have not checked to see of it will work on my LAN using latest release. I will check and get back.

**Comment by frboyer** [comment] 2017-08-19 15:39
This is most probably caused by issue #84 I posted this morning.

**Comment by jean-emmanuel** [comment] 2017-08-19 15:48
This should be fixed in v0.19.2 then :)

**Comment by Schroedingers-Cat** [comment] 2017-08-27 21:16
I'm using v0.19.6 with the ardour template but any iOS device (9.3 and 10.5) running Chrome 60 just open a blue blank page. Furthermore, the online demo cannot load any templates.

Everything works fine when accessing from Windows/Firefox or Android/Firefox.

**Comment by jean-emmanuel** [comment] 2017-08-28 06:27
Can you run the server from a terminal and check for error messages ?

**Comment by Schroedingers-Cat** [comment] 2017-08-28 10:42
I may be doing something wrong with the terminal. I start up a powershell 5 and start the server with
```powershell
.\open-stage-control.exe -d
```
I connect from Win/FF to the server. I get asked which file to load on the client and I chose ardour.js. I change any parameter but there is not a single output in the terminal. So how do I get to see the terminal output?

When I connect from iOS 10 via Chrome or Safari, I'm asked which file to load. However I cannot select anything but files that are stored locally on the iPad (`Take a photo or video`, `local photo media`, `iCloud Drive`). When I click on "New" instead, I'm in the editor mode but can only add new tabs to the layout. It seems to me there is a problem in communicating certain things that are on the server to the iOS device.

This is happening on an iPad Air 2 as well as an iPad 2. It's likely to be hardware independent as it occurs across different versions of iOS and devices.

**Comment by jean-emmanuel** [comment] 2017-08-28 16:59
> So how do I get to see the terminal output?

You'd have to set targets for widgets or a global target via the `--sync` command line option to see osc logs activated by the  `--debug / -d` option, although errors are printed regardless of this option.

> When I connect from iOS 10 via Chrome or Safari

Please note that Safari is unlikely to work as it's not supported

> I'm asked which file to load

Do you see the list of recently opened sessions ? None of them can be opened ?

> However I cannot select anything but files that are stored locally on the iPad 

That's by design, you can't browse the server's files.

> When I click on "New" instead, I'm in the editor mode but can only add new tabs to the layout.

Do you mean you can't select anything else than the root panel ?

**Comment by Schroedingers-Cat** [comment] 2017-08-28 17:26
This time, I started the server with
```powershell
.\open-stage-control.exe -d -s
```
I don't get any error messages. Not sure however, how to use the -s parameter as it synchronizes hosts, but only one host is used in this setup.

When I access the server from my Android device with Firefox, I see this screen:  

![grafik](https://user-images.githubusercontent.com/6382400/29784773-96faec46-8c25-11e7-80e3-c49e8c228620.png)
I can load the template and use it.

However, when using iOS/Chrome, the List under "Open Stage Control" is empty. Is this really by design?

**Comment by jean-emmanuel** [comment] 2017-08-28 17:49
> I don't get any error messages. 

Ok, gotta dig that, it might take some time since I don't own an iOS device

> Not sure however, how to use the -s parameter as it "synchronizes hosts", but only one host is used in this setup.

It defines one or multiple default targets for the widgets (as stated in the docs: « osc messages sent by widgets will also be sent to these targets »)

> However, when using iOS/Chrome, the List under "Open Stage Control" is empty. Is this really by design?

Nope, only the "browse" action part is, this looks like a bug indeed, Chrome has had some weird iOS specific issues on iOS.

**Comment by Schroedingers-Cat** [comment] 2017-08-28 18:00
> It defines one or multiple default targets for the widgets (as stated in the docs: « osc messages sent by widgets will also be sent to these targets »)  

Makes sense. The help text from the command line made me think the other way:
>   -s, --sync           synchronized hosts (ip:port pairs)                [array]


> Ok, gotta dig that, it might take some time since I don't own an iOS device  

I could wipe my iPad and give you remote access via TeamViewer if that would be of help?

**Comment by jean-emmanuel** [comment] 2017-08-29 06:28
> Makes sense. The help text from the command line made me think the other way:

I have to update the help message then !

> I could wipe my iPad and give you remote access via TeamViewer if that would be of help?

Thanks a lot for the offer, but I might have found the

**Comment by Schroedingers-Cat** [comment] 2017-08-29 10:41
I accessed openstagecontrol.herokuapp.com with Chrome 60.0.3112.89 on iOS 9.3 but I'm not shown any .js files to load the template.

**Comment by jean-emmanuel** [comment] 2017-08-30 06:18
New attempt, the list should be visible now, is it ?

**Comment by Schroedingers-Cat** [comment] 2017-08-30 07:11
That fixed it.  
![img_0003](https://user-images.githubusercontent.com/6382400/29859574-0d2a5986-8d63-11e7-8c6d-446363b04716.PNG)

However, when I load the Ardour.js file, I get this:  
![img_0004](https://user-images.githubusercontent.com/6382400/29859591-1e90aa9a-8d63-11e7-97d4-223362a6a6fa.PNG)

and after some seconds this "empty" template:  
![img_0005](https://user-images.githubusercontent.com/6382400/29859603-2b6b7934-8d63-11e7-9afe-3a94cfe69677.PNG)

This also happens on an iPad Air 2 with iOS 10.

**Comment by jean-emmanuel** [comment] 2017-08-30 13:49
Alright, ii seems to be caused by a [bug in Safari < 10.1](https://bugs.webkit.org/show_bug.cgi?id=136041) (chrome on iOS runs on top of Safari's engine, Apple's policy...). Commit 25b75f739a1bd399cc8d87dd71e05385e4689c1c attempts to fix it.

**Comment by Schroedingers-Cat** [comment] 2017-08-30 14:13
Right now, my iPad 2 (iOS 9.3) does not show any .js files when accessing openstagecontrol.herokuapp.com with Chrome, Firefox or Safari.

**Comment by jean-emmanuel** [comment] 2017-08-30 14:19
Ok thanks for testing, more to come soon !

**Comment by jean-emmanuel** [comment] 2017-08-31 06:45
Ok, now that I have access to iOS devices emulators (browserstack, yeah!), I can confirm that Chrome on iOS has very few to do with the regular Chrome I intended to support when I started this project : different javascript engine, different rendering engine, it's not much more than a themed Safari... The issue here is due to some bugs in Safari regarding a css feature called flexbox which I use a lot to create the app's layouts. I'll try to fix them, to be continued...

**Comment by Schroedingers-Cat** [comment] 2017-08-31 10:39
Thank you for looking into it and for the updates!

**Comment by jean-emmanuel** [comment] 2017-09-01 13:42
Getting better I think, can you confirm ?

**Comment by Schroedingers-Cat** [comment] 2017-09-01 13:54
Absolutely!  
![img_0007](https://user-images.githubusercontent.com/6382400/29972828-c67fb98c-8f2d-11e7-912d-cdd370e42c8d.PNG)

Some text rendering (like "Trim" or "0") are a bit off - does that happen on your device too?

**Comment by jean-emmanuel** [comment] 2017-09-01 14:22
Cool ! Yes, not fixed yet ;)

**Comment by jean-emmanuel** [comment] 2017-09-01 16:55
Almost done here !

**Comment by guitmart** [comment] 2017-09-02 03:03
Hi Jean-Emmanuel,
All faders don't move on IOS 9.3 but all buttons response.
Thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-09-01 12:55 GMT-04:00 jean-emmanuel <notifications@github.com>:

**Comment by Schroedingers-Cat** [comment] 2017-09-02 08:51
All the text is now positioned correctly, great!

Can confirm that sliders/faders and knobs cannot be moved. But buttons react to touch.

**Comment by jean-emmanuel** [comment] 2017-09-02 14:13
Found it !

**Comment by Schroedingers-Cat** [comment] 2017-09-02 21:02
Yes, faders work as well now.

Does the Fullscreen button work for you?

**Comment by guitmart** [comment] 2017-09-03 01:02
The fader work but the fullsceen, no.
Thanks for the great job Jean Emmanuel

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-09-02 17:02 GMT-04:00 Schroedingers-Cat <notifications@github.com>:

**Comment by mrpastewart** [comment] 2017-09-03 02:13
way to go getting this moving.

**Comment by mrpastewart** [comment] 2017-09-03 02:27
When I load on my iPAD Pro it will load but it pops up a window on launch that says "undefined" that I have to close in order to access template. Also no full screen and can't load a project when opening editor mode. Also I can confirm that this is also starting to work on Safari on iOS.

**Comment by jean-emmanuel** [comment] 2017-09-04 18:07
I'm closing this issue and opening some new ones for the problems you mentioned, stay tuned ;)

**Closed by jean-emmanuel** 2017-09-04 18:07 UTC
