### ISSUE TITLE
[Feature] Warn the user if there's something wrong with a custom module

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#529] opened 2019-06-03 12:52 UTC
It prevents any session to be opened (see https://openstagecontrol.discourse.group/t/no-window-opens-anymore-when-pushing-start/102).

**Comment by jean-emmanuel** [comment] 2019-06-11 08:04
Errors encountered in the custom module are supposed to be printed in the console already, could you upload you custom module file ?

**Comment by nesdnuma** [comment] 2019-06-11 08:26
Sure. Here it is, but as stated, there was a typo in the code.

var time_zero = Date.now();

function resetTimer() {
    time_zero = Date.now()
    setTimer(0)
}

```
function setTimer(time){
    
	/*var numsecs = time / 1000,
		s = Math.floor(numsecs) % 60,
		nummin = numsecs / 60 - s,
		m = Math.floor(nummin) % 60,
		numhours = nummin / 60  - m,
		h = Math.floor(numhours) % 24
	*/
	var h = Math.floor(time / 3600) % 24,
        m = Math.floor((time - h * 3600) / 60),
        s = Math.round((time - m * 60)) % 60
    //var h = Math.floor(time / 3600),
    //    m = Math.floor((time - h * 3600) / 60),
    //    s = Math.round((time - m * 60))

    receiveOsc({
        address: '/timer',
        args: [
            {
                type: 's',
                //value: `${m<10?'0':''}${m}:${s<10?'0':''}${s}`
				value: `${h<10?'0':''}${h}:${m<10?'0':''}${m}:${s<10?'0':''}${s}`
            }
        ]
    })
}

module.exports = {

    init: function(){

        resetTimer()

        setInterval(()=>{

            setTimer((Date.now() - time_zero )/ 1000)

        }, 1000)
        
    },

    oscOutFilter: function(data) {

        var {address, args, host, port} = data

        if (address === '/timer/reset') {
            return resetTimer()
        }

        return data
    
    }

}
```

**Comment by jean-emmanuel** [comment] 2019-06-16 08:09
Ok if you have encounter the issue again please provide something a reproduce it. Closing for now because as far as I can tell custom module errors are already printed in the console.

**Closed by jean-emmanuel** 2019-06-16 08:09 UTC
