### ISSUE TITLE
TypeError when connecting

### ISSUE THREAD

**Issue by jamols** [jean-emmanuel/open-stage-control#417] opened 2018-11-05 22:57 UTC
v0.39.4 freezes at "Connecting Server..." on the following:
* iPhone 6, iOS 10.3.3
* iPad 3, iOS 9.3.5

Server log:

[Renderer process error]
TypeError: Invalid attempt to spread non-iterable instance
at http://169.254.55.60:8080/client/open-stage-control-client.js:513:217
(no stacktrace available)

**Comment by jean-emmanuel** [comment] 2018-11-06 13:18
There seem to be a regression in the transpilation proceess since f3681a1be02b0e21d36d9d60a44c38fae8348068. To be fixed asap !

**Comment by jean-emmanuel** [comment] 2018-11-06 19:17
Should be fixed in v0.39.5

**Closed** 2018-11-07 11:43 UTC

**Comment by jamols** [comment] 2018-11-08 21:50
Client (iOS 9.3.5) is now seeing this error when loading any existing project I have, where the desktop client loads them perfectly:

<I CLASS+"FA FA-FW FA-EXCLAMATION-TRIANGLE"></I>&NBSP; PARSING ERROR.

Server log shows a similar error message as before with different line numbers:

[Renderer process error]
TypeError: Invalid attempt to spread non-iterable instance
at http://192.168.2.1:8080/client/open-stage-control-client.js:570:1525
(no stacktrace available)

Not sure if it's a different issue?

Thanks!

**Comment by jean-emmanuel** [comment] 2018-11-08 22:46
Ok, still the same issue, I'll dig that soon

**Comment by jean-emmanuel** [comment] 2018-11-09 01:11
Could you try again with v0.39.7 ?

**Comment by jamols** [comment] 2018-11-14 22:50
0.39.8 works well so far, thank you!
