### ISSUE TITLE
[Bug] Blank server on v0.49.x (running Windows 7 x64)

### ISSUE THREAD

**Issue by hellishvictor** [jean-emmanuel/open-stage-control#599] opened 2020-03-15 16:11 UTC
Hi, this is what I get when I launch **open-stage-control.exe** with any **v0.49.x**:
![sshot-1](https://user-images.githubusercontent.com/34694956/76705301-f5237e80-66d6-11ea-8d55-22544d55b482.jpg)

No problems at all with v0.48.8. I'm on Win7 x64 with the latest version of Python installed.

**Comment by jean-emmanuel** [comment] 2020-03-15 17:33
Moved from #152 

> Is possible disable the "check for updates" feature so it stops showing the message **[V0.49.x IS AVAILABLE]**? And btw, its possible set another location for the **Cache** folder  instead of **AppData/Roaming**? On the same folder where the program is installed would be acceptable.

_Originally posted by @hellishvictor in https://github.com/jean-emmanuel/open-stage-control/issues/152#issuecomment-599231318_

**Comment by jean-emmanuel** [comment] 2020-03-15 17:40
> Is possible disable the "check for updates" feature so it stops showing the message [V0.49.x IS AVAILABLE]

In v1 there will be an option for this.

> And btw, its possible set another location for the Cache folder instead of AppData/Roaming

This seem to be also discussed upstream (https://github.com/electron/electron/issues/1404), I'll have to dig this. 

Could it be that your 2 posts are linked ? Have you tried removing that cache folder to solve your issue ?

**Comment by hellishvictor** [comment] 2020-03-15 18:16
> > Is possible disable the "check for updates" feature so it stops showing the message [V0.49.x IS AVAILABLE]
> 
> In v1 there will be an option for this.
v1? and for when you think that version will be released, in about a year? right now its v0.49 (which so far don't launch here).
> 
> > And btw, its possible set another location for the Cache folder instead of AppData/Roaming
> 
> This seem to be also discussed upstream ([electron/electron#1404](https://github.com/electron/electron/issues/1404)), I'll have to dig this.
> 
> Could it be that your 2 posts are linked ? Have you tried removing that cache folder to solve your issue ?
Yes, and it doesn't solve; seems that they're not linked. All I know that all the versions v0.49.x don't work for me.

**Comment by jean-emmanuel** [comment] 2020-03-15 18:46
> v1? and for when you think that version will be released, in about a year? right now its v0.49 (which so far don't launch here).

This sounds a bit aggressive, please keep in mind that this software comes with absolutely no warranty of any kind. v1 will be released when it's ready. 

> Yes, and it doesn't solve; seems that they're not linked. All I know that is all the versions v0.49.x don't work for me.

Could you try running the executable from a terminal and report error messages if any ?

**Comment by hellishvictor** [comment] 2020-03-15 19:07
Here is (it didn't stop as long as the OSC server is running):

[3620:0315/190149.665:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.965:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Internal D3D11 error: HRESULT: 0x8007000E: LoadLibrary failed to load D3D C
ompiler DLL.
[3812:0315/190149.967:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.967:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.968:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.969:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.970:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.970:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.971:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.971:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.972:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.973:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.974:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.984:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.985:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.985:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.995:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.996:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190149.997:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.010:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.011:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.012:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.026:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.027:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.027:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.037:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.037:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.038:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.039:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.039:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.040:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.040:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3812:0315/190150.041:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.312:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Internal D3D11 error: HRESULT: 0x8007000E: LoadLibrary failed to load D3D C
ompiler DLL.
[3800:0315/190150.313:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.314:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.314:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.315:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.315:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.316:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.317:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.317:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.318:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.319:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.320:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.329:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.330:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.330:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.343:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.344:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.345:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.360:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.361:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.362:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.376:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.377:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.377:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.383:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.384:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.384:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.385:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.385:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.386:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.386:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3800:0315/190150.387:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.655:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Internal D3D11 error: HRESULT: 0x8007000E: LoadLibrary failed to load D3D C
ompiler DLL.
[3948:0315/190150.656:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.657:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.657:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.658:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.659:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.660:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.660:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.661:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.662:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.662:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.663:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.669:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.670:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.670:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.676:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.677:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.678:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.692:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.693:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.694:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.709:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.710:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.710:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.727:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.728:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.728:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.729:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.730:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.731:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.732:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.732:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.733:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.733:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[3948:0315/190150.734:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.001:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Internal D3D11 error: HRESULT: 0x8007000E: LoadLibrary failed to load D3D C
ompiler DLL.
[4084:0315/190151.002:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.002:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.003:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.004:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.004:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.006:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.006:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.007:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.008:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.010:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.011:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.018:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.019:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.019:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.028:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.029:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.029:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.044:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.045:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.046:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.060:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.061:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.061:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.073:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.074:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.075:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.075:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.076:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.077:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.077:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
[4084:0315/190151.078:ERROR:gl_utils.cc(325)] [.DisplayCompositor] GL_OUT_OF_MEM
ORY: Context has been lost.
`

**Comment by jean-emmanuel** [comment] 2020-03-15 19:17
It seems there's a compatibility between the engine (chromium/electron) and your gpu. You may confirm this by running `open-stage-control.exe --disable-gpu`. I can't help with that unfortunately, besides hoping it's fixed a more recent version of the enging.

**Comment by hellishvictor** [comment] 2020-03-15 19:54
It skipped the server window, but the GUI show up it was possible load a session. Also is possible open it through the http://127.0.0.1:8080 on a browser (Firefox), and here, the widgets worked better on the browser (on the GUI window the fader work weird). In both cases I can't send midi :(
Good that finally I've contacted you here, I've been sending emails the last weeks. 
Thank you for the support and look forward for the next releases.

**Comment by jean-emmanuel** [comment] 2020-03-15 20:24
> the fader work weird, check the image

I guess that's caused by the gpu acceleration beeing disabled.

I'm uploading v0.49.8, hopefully this will fix it

**Comment by jean-emmanuel** [comment] 2020-03-15 20:33
> And btw, its possible set another location for the Cache folder instead of AppData/Roaming

Back on this topic, I'll stick to the default for now (seems to be pretty standard and widely spread), but I'll add a command-line only option to allow specifying a different folder.

**Comment by hellishvictor** [comment] 2020-03-15 20:50
> 
> 
> > And btw, its possible set another location for the Cache folder instead of AppData/Roaming
> 
> Back on this topic, I'll stick to the default for now (seems to be pretty standard and widely spread), but I'll add a command-line only option to allow specifying a different folder.



> 
> 
> > the fader work weird, check the image
> 
> I guess that's caused by the gpu acceleration beeing disabled.
> 
> I'm uploading v0.49.8, hopefully this will fix it

Great, waiting for test it and see how it goes (so far only are uploaded the source codes in "Assets")

**Comment by hellishvictor** [comment] 2020-03-15 20:52
> 
> 
> > And btw, its possible set another location for the Cache folder instead of AppData/Roaming
> 
> Back on this topic, I'll stick to the default for now (seems to be pretty standard and widely spread), but I'll add a command-line only option to allow specifying a different folder.

Windows' temp folder would be also a good choice. In any case, I'll add them to CCleaner's list of folder to remove xD

**Comment by jean-emmanuel** [comment] 2020-03-15 20:58
> so far only are uploaded the source codes in "Assets"

should be there now

**Comment by hellishvictor** [comment] 2020-03-15 20:59
> 
> 
> > v1? and for when you think that version will be released, in about a year? right now its v0.49 (which so far don't launch here).
> 
> This sounds a bit aggressive, please keep in mind that this software comes with absolutely no warranty of any kind. v1 will be released when it's ready.

Well, now with v0.49.8 we are more close to v1.0 xD

> I'll add a command-line only option to allow specifying a different folder

It would be really awesome if you do the same with the ".open-stage-control" file stored on "C:\Users\Administrador"; I want to keep it on the installation folder and run o-s-c as portable.

**Comment by hellishvictor** [comment] 2020-03-15 21:22
> 
> 
> > so far only are uploaded the source codes in "Assets"
> 
> should be there now

Now the server window doesn't show up at all, but the services are running on the background.
With the  "--disable-gpu" command it keeps weird.

![sshot-1](https://user-images.githubusercontent.com/34694956/76710873-e5219400-6702-11ea-9ceb-6bd29f903ed4.jpg)

**Comment by jean-emmanuel** [comment] 2020-03-15 22:51
I've reproduced the glitch with `--disable-gpu` and i'll fix it in v1. Have you managed to run a regular chrome browser on this system ?

**Comment by hellishvictor** [comment] 2020-03-15 23:11
Yes, and so far I do prefer Firefox :)

**Comment by jean-emmanuel** [comment] 2020-03-16 08:41
Note that firefox support is not planned, it may work but bugs won't be addressed.

**Comment by jean-emmanuel** [comment] 2020-03-17 17:46
As of v0.49.10 --disable-gpu doesn't bypass the launcher window. Reported glitches are prevented as well in the built-in gui. The gpu compatibility issue remains but is could only be fixed upstream.

**Closed by jean-emmanuel** 2020-03-17 17:46 UTC

**Comment by hellishvictor** [comment] 2020-03-17 18:13
The binares are not available yet, only the source codes... seems they take forever to upload.

**Comment by hellishvictor** [comment] 2020-03-17 18:19
The icon display bad on the lower views on explorer (detailed view) because it only has the 256 size.
The following file include the sizes 16,24,32,48,128 & 256 and fix that:
 [IconGroup1.zip](https://github.com/jean-emmanuel/open-stage-control/files/4345059/IconGroup1.zip)

**Comment by hellishvictor** [comment] 2020-03-17 19:37
> 
> 
> As of v0.49.10 --disable-gpu doesn't bypass the launcher window. Reported glitches are prevented as well in the built-in gui when --disable-gpu is set. The gpu compatibility issue remains but can only be fixed upstream.



> 
> 
> As of v0.49.10 --disable-gpu doesn't bypass the launcher window. Reported glitches are prevented as well in the built-in gui when --disable-gpu is set. The gpu compatibility issue remains but can only be fixed upstream.

Now it does work; it shows the server, the client GUI and the midi, but I can't see the option for "Relaunch" on the server, only "copy, paste, midi and console", so in the case I need to do it, I have to close and launch again the server, scroll down and press Start... :S However, I'll create a shortcut with "open-stage-control --disable-gpu".
One more thing: there's 5 services running, of which one is for the GUI client, and the other four for the App available at the four https, right? there's a option for select which should be enabled? There's cases when I only run the client GUI (or just the "http://127.0.0.1:8080" on my browser
 and I'll prefer have nothing running in the background (for save system resouces).

**Comment by jean-emmanuel** [comment] 2020-03-17 19:42
Relaunch has been removed in v0.49.6, it doesn't work with current engine's version.

> there's 5 services running

That's chromium's process architecture, you can't do anything about it.

**Comment by jean-emmanuel** [comment] 2020-03-17 19:50
> you can't do anything about it.

Well if you need to spare resources, you can run the server in headless mode with node : https://openstagecontrol.ammd.net/docs/getting-started/#running-without-electron
This way you'd only have 1 server process and the client processes (ie browsers) would be up to you to manage.

**Comment by hellishvictor** [comment] 2020-03-17 20:24
I have no idea what node is. With the following:
`open-stage-control --disable-gpu --send 127.0.0.1:5555 --port 7777 --midi toloopMIDI:0,1`
the server window doesn't show up, and the client does with midi working, but still there's three servers running on the background. I though that since I've included one url on the send command there's will be only one (besides the server and the client).
![sshot-1](https://user-images.githubusercontent.com/34694956/76897416-a10dcb00-688b-11ea-9ec1-c9f7c1729e4f.jpg).

**Comment by jean-emmanuel** [comment] 2020-03-17 22:28
> I have no idea what node is

Clicking on the link, reading the docs and doing some research could help.

> the server window doesn't show up

That's expected, the launcher is just an interface that builds the command line. It's not needed when options are provided directly.

>  I though that since I've included one url on the send command there's will be only one

As I said, that's how chromium (the engine) works : https://www.chromium.org/developers/design-documents/multi-process-architecture.

**Comment by hellishvictor** [comment] 2020-03-17 23:31
> 
> 
> > I have no idea what node is
> 
> Clicking on the link, reading the docs and doing some research could help.
> 

Yeah, testing hours ago another software I noticed it was one of its components; seems its used everywhere these days. But get into Node will means have more services running on the background = something I try to avoid on my system.

Cheers.
