### ISSUE TITLE
[possible bug] when saving Session 

### ISSUE THREAD

**Issue by schoko11** [jean-emmanuel/open-stage-control#672] opened 2020-12-02 14:56 UTC
[OpenStageControl4reaper_13.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/5630026/OpenStageControl4reaper_13.json.zip)

when loading this i got a console error because of an undefined or null object (line 3, kempStompAFXSel, label property) when try to fix that i hit save and then when closing the session i got a warning because of unsafed changes (the popup says successfully saved).
Apart from that i can't alter the JS in the property(sometimes it works after several tries.. ?), hitting "no" on the warning always closes the client session(not what i expect)...

Thanks!

**Comment by jean-emmanuel** [comment] 2020-12-02 15:06
> when loading this i got a console error because of an undefined or null object (line 3, kempStompAFXSel, label property) 

That not a bug but an error occurring when the code is executed before the @{} blocks have a value, the only way to avoid it is to provide a fallback value (eg `var x = @{widget_id} || {}`)

> when try to fix that i hit save and then when closing the session i got a warning because of unsafed changes (the popup says successfully saved).
Apart from that i can't alter the JS in the property(sometimes it works after several tries.. ?), hitting "no" on the warning always closes the client session(not what i expect)...

I'll need more details on how to reproduce this error.

**Comment by schoko11** [comment] 2020-12-02 15:36
Thanks, will try to fix that.

I just can describe you what i did.
open the session
enable the editor
go to tab kemper
go to widget "kempStompAFXSel
edit label property
hit save
when stopping the server the alert of unsafed changes come up.

**Comment by jean-emmanuel** [comment] 2020-12-02 15:40
what version of o-s-c are you using ?

Le 02/12/2020 à 16:36, schoko11 a écrit :

**Comment by schoko11** [comment] 2020-12-02 15:47
1.7.3

**Comment by jean-emmanuel** [comment] 2020-12-02 15:59
I just followed these steps with 1.7.3 (built-in client) and did not 
encountered any error or strange behavior.

Le 02/12/2020 à 16:48, schoko11 a écrit :

**Comment by schoko11** [comment] 2020-12-02 17:13
That is a little bit weird, because i can't save the session, i opened up the json file and copied in the JS code.
(there were no " in it, so had not to escape this with \). After saving the  json file, i couldn't open it(json parse error). Then i deleted some blanks(i thought i could spot the position) and added \n linebreaks. Notepad++ is at (Unix LF utf-8 computer is WIN10), maybe i copied in some "illegal char" that breaks it...

**Comment by jean-emmanuel** [comment] 2020-12-02 17:38
Maybe https://jsonchecker.com/ could help

**Comment by jean-emmanuel** [comment] 2020-12-06 20:35
Closing for now. Feel free to reopen if more informations come up.

**Closed by jean-emmanuel** 2020-12-06 20:35 UTC
