### ISSUE TITLE
bug:  text in panel nested in strip pulls over to the left in its clones

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#233] opened 2018-03-13 04:16 UTC
in the image below you can see the text that is selected is centered but the clones of the fader pull to the left and are missing some text. this doesn't happen all the time but sometimes. Sometimes led's in clones disappear too

<img width="1384" alt="screenshot_2018-03-12 21 11 26_uhcawm" src="https://user-images.githubusercontent.com/28813706/37322352-39685b7c-263a-11e8-8908-bc456c21bd2e.png">

**Comment by Sebastian-blu** [comment] 2018-03-13 05:01
this is an example of clones not showing the LED's if you look at the first one row one column one

you see the red led's are not showing in the clones. this is inconsistent, sometimes they are there sometimes they are not 

<img width="1060" alt="screenshot_2018-03-12 21 57 38_xrl4rs" src="https://user-images.githubusercontent.com/28813706/37323375-94f9358c-2640-11e8-9981-c640bafa8d1b.png">

**Comment by Sebastian-blu** [comment] 2018-03-13 05:45
this might also be part of the problem

slider and a panel group of buttons both in a panel together

they both have a left value of 25%

<img width="178" alt="screenshot_2018-03-12 22 42 57_hecj3l" src="https://user-images.githubusercontent.com/28813706/37324474-d23b2698-2646-11e8-8c67-2170aff75617.png">

**Comment by cyberic99** [comment] 2018-03-13 07:33
beautiful stuff!

once finished, please make some screenshots!

**Comment by jean-emmanuel** [comment] 2018-03-14 11:42
Please send some session file, I can't reproduce the issue.

**Comment by Sebastian-blu** [comment] 2018-03-14 18:13
[barryCleanBitwigControl copy.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1812416/barryCleanBitwigControl.copy.json.txt)

**Comment by Sebastian-blu** [comment] 2018-03-14 18:14
the slider and record solo mute buttons above are found on the device page

**Comment by jean-emmanuel** [comment] 2018-03-15 08:44
- slider / panel alignment: remove the css margin from the slider
- disapearing leds: turn the panels that contains 2 leds into strips, they are better at handling this kind of layout
- push size  inconsistency (not mentionned but I just saw that); disable the `scroll` property in the panel that contains the led and push.

**Comment by jean-emmanuel** [comment] 2018-03-16 12:39
I'm closing this since the problem seems to be nothing but a rendering bug on the browser's side and the workaround is trivial.

**Closed by jean-emmanuel** 2018-03-16 12:39 UTC
