### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by mrsstaceyseigle** [jean-emmanuel/open-stage-control#404] opened 2018-10-24 07:09 UTC
Can Open stage control build, compile for android os. 

I like to install on android as android will be the server.

**Comment by jean-emmanuel** [comment] 2018-10-24 07:46
No, open-stage-control is not designed this way. There seem to be solutions to run node on android though, so maybe running in headless mode [with node](https://github.com/jean-emmanuel/open-stage-control/issues/368#issuecomment-427429570) is possible, but I wouldn't bet on it.

**Comment by jean-emmanuel** [comment] 2018-10-24 07:53
-> https://github.com/electron/electron/issues/9162#issuecomment-362978842
I can't try that, but if you manage to get it working, I'd be happy to add instructions in the docs

**Comment by mrsstaceyseigle** [comment] 2018-10-24 08:34
I will give it a try and will report back here. 

In order to run headless do we have to compile the source code or do we just download the source code as is and just run the correct commands in node. 

Also would you be able to provide headless commands

**Comment by jean-emmanuel** [comment] 2018-10-24 08:44
You need to follow the "[run from sources](http://osc.ammd.net/getting-started/#run-from-sources)" instructions except that you run the app with "`node /path/to/app/ --no-gui`" instead of "`npm start`". Commands are documented [here](http://osc.ammd.net/getting-started/#options).
You'll probably have to remove some dependencies by hand from package.json, such as https://github.com/jean-emmanuel/open-stage-control/blob/master/package.json#L30

**Comment by jean-emmanuel** [comment] 2018-10-24 09:28
`C:\Users\mrsst\UsersmrsstDownloadsopen-stage-control-0.38.4-win32-x64\app` doesn't exist, try `C:\Users\mrsst\UsersmrsstDownloadsopen-stage-control-0.38.4-win32-x64\resources\app`

**Comment by jean-emmanuel** [comment] 2018-10-24 09:38
(http://osc.ammd.net/getting-started/#running-without-electron)

**Comment by mrsstaceyseigle** [comment] 2018-10-24 09:40
So in order to get it to work I need to first install xvfb
<https://en.wikipedia.org/wiki/Xvfb>. Is that correct

**Comment by jean-emmanuel** [comment] 2018-10-24 09:44
No, this is only needed in a true headless environnement (without a display/window manager) and not requiered when running with node. I was just pointing out the next parargraph (Running without Electron).

**Comment by mrsstaceyseigle** [comment] 2018-10-24 09:53
![1](https://user-images.githubusercontent.com/43449594/47422661-281b4a00-d751-11e8-9331-35d953a5e6de.png)
![2](https://user-images.githubusercontent.com/43449594/47422662-281b4a00-d751-11e8-9ee3-06561204282f.png)
![3](https://user-images.githubusercontent.com/43449594/47422663-281b4a00-d751-11e8-8e6b-db21d9964331.png)
![4](https://user-images.githubusercontent.com/43449594/47422664-281b4a00-d751-11e8-9ac2-e2805432d501.png)

**Comment by jean-emmanuel** [comment] 2018-10-24 10:11
The program failed to recognized node under windows, it should be fixed with latest commit. I also made it enable --no-gui automatically when running with node.

**Comment by mrsstaceyseigle** [comment] 2018-10-24 17:21
So should I redownload the package

**Comment by jean-emmanuel** [comment] 2018-10-24 17:44
The're has been no new release so you gotta run `git pull` and package it yourself (note that you can also just run from sources without packaging, as explained in the docs).

**Comment by mrsstaceyseigle** [comment] 2018-10-24 18:19
really sorry to bother you with this. Just trying to get this to run
headless on windows so that I can later try on android. So I tried to run
it directly from the source after git pull.   here is the last error receive

$ node /c:/open-stage-control/open-stage-control/app/ -n
internal/modules/cjs/loader.js:582
    throw err;
    ^
Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename
(internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous>
(c:\open-stage-control\open-stage-control\app\main\settings.js:94:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

**Comment by mrsstaceyseigle** [comment] 2018-10-24 18:34
Seem to be a hard one.

Tried the followings
npm install
bash
node /c:/open-stage-control/open-stage-control/app/ -n


Errors:
$ node /c:/open-stage-control/open-stage-control/app/ -n
c:\open-stage-control\open-stage-control\app\main\main.js:18
    require('electron').dialog.showErrorBox = (title, err)=>{
                                            ^
TypeError: Cannot set property 'showErrorBox' of undefined
    at Object.<anonymous>
(c:\open-stage-control\open-stage-control\app\main\main.js:18:45)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous>
(c:\open-stage-control\open-stage-control\app\index.js:1:63)
    at Module._compile (internal/modules/cjs/loader.js:688:30)

**Comment by jean-emmanuel** [comment] 2018-10-24 19:59
Ok that's better, we're back to the error caused by the misdetection of node under windows, could you check that `app\main\main.js`  contains this line: https://github.com/jean-emmanuel/open-stage-control/blob/master/app/main/main.js#L6 ?

**Comment by mrsstaceyseigle** [comment] 2018-10-24 20:06
main.js does not contain that line. 
I have attached the file here. Just change the file extension from .txt to .js
[main.txt](https://github.com/jean-emmanuel/open-stage-control/files/2512128/main.txt)

**Comment by jean-emmanuel** [comment] 2018-10-24 20:19
This means your local git repository is not up to date, maybe `git pull origin master` again ?

**Comment by jean-emmanuel** [comment] 2018-10-25 06:52
I didn't took the time to open your file yesterday, but it appears it does contain that line... I pushed a new commit to try to fix the problem, can you pull and try again ?

**Comment by jean-emmanuel** [comment] 2018-10-25 13:32
Seems to be possible after all ! Check out #405

**Comment by cyberic99** [comment] 2018-10-25 13:44
@mrsstaceyseigle if something is not clean enough, don't hesitate to ask it in #405.

After all, it o-s-c seems easier to build on android than on windows ;-)

**Comment by mrsstaceyseigle** [comment] 2018-10-25 17:50
The last commit fixed. We are now running headless.  one small error After going to localhost:8080


mrsst@LAPTOP-T05A9IJO MINGW64 /c/open-stage-control/open-stage-control (master)
$ node /C:/open-stage-control/open-stage-control/app/ -n
Running with node
App available at http://192.168.56.1:8080 & http://192.168.64.2:8080 & http://127.0.0.1:8080



once I go to localhost:8080   I get the following error

mrsst@LAPTOP-T05A9IJO MINGW64 /c/open-stage-control/open-stage-control (master)
$ node /C:/open-stage-control/open-stage-control/app/ -n
Running with node
App available at http://192.168.56.1:8080 & http://192.168.64.2:8080 & http://127.0.0.1:8080
Error: ENOENT: no such file or directory, stat 'C:\open-stage-control\open-stage-control\app\browser\styles.css'
Error: ENOENT: no such file or directory, stat 'C:\open-stage-control\open-stage-control\app\browser\scripts.js'

**Comment by mrsstaceyseigle** [comment] 2018-10-25 19:33
Everything is working great now with the updated commit.

**Comment by jean-emmanuel** [comment] 2018-10-25 21:33
Great ! I'm closing this since #405 seems more advanced on the initial topic

**Closed by jean-emmanuel** 2018-10-25 21:33 UTC

**Comment by mrsstaceyseigle** [comment] 2018-10-25 23:48
Before closing please allow me to ask this question. Can you please make an Android Version of this software. PLEASE

**Comment by jean-emmanuel** [comment] 2018-10-26 07:40
Haha, don't worry you can still ask questions even if it's closed ! There won't be an official android version nor an iOS version anytime soon as 1. the main goal of the project is to provide a desktop app 2. I don't have the hardware and the free time required to work on that.

**Comment by jean-emmanuel** [comment] 2018-10-26 16:12
But again, #405 seem to provide that in a way :)
