### ISSUE TITLE
[Bug] Layout not displayed 1.7.0 beta3

### ISSUE THREAD

**Issue by CtrlZ-Music** [jean-emmanuel/open-stage-control#667] opened 2020-11-16 11:15 UTC
When opening a patch with a console.log() inside the patch and the console is open
the patch is not displayed. (black screen)
close the console view the patch is displayed correctly.

**Comment by jean-emmanuel** [comment] 2020-11-16 17:40
I'm unable to reproduce this with only the informations you provided.

**Comment by jean-emmanuel** [comment] 2020-11-18 18:30
Closing until more informations come up.

**Closed by jean-emmanuel** 2020-11-18 18:30 UTC
