### ISSUE TITLE
Rearranging the order of the widgets in a strip element broken

### ISSUE THREAD

**Issue by git-moss** [jean-emmanuel/open-stage-control#183] opened 2018-03-03 18:16 UTC
After drag & drop a widget to reorder the widgets all widgets seem to get shuffled in a random order.
(As a workaround I changed the order in the JSON file).

Tested with the navigation strip of the Ardour example.

Windows 10 64 bit.

**Comment by jean-emmanuel** [comment] 2018-03-03 18:46
Duplicate of #175, the fix is in git and will be included in next release.
Thanks for your feedback!

**Closed by jean-emmanuel** 2018-03-03 18:46 UTC
